### PR TITLE
update readme with .net lambda serverless api config info

### PR DESCRIPTION
**Pull request by brignolij**
## Description
Add informations in the readme to make work Amazon.Extensions.Configuration.SystemsManager in case of use .net lambda Serverless template

## Motivation and Context
When using Amazon.Extensions.Configuration.SystemsManager with .net lambda serverless template, default configuration cause configuration conflict and the Amazon.Extensions.Configuration.SystemsManager make the app crash. With these information in the readme, it's simple to make it work.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-dotnet-extensions-configuration/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by mgorski-mg** [comment]
There is information about this mechanism already in the 'Configuring Systems Manager Client' section.
You can add details about the problem in this section :)

**Comment by brignolij** [comment]
@mgorski-mg thanks for your update, I updated my pr.

**Review by mgorski-mg — APPROVED** [review]

**Comment by mgorski-mg** [comment]
@brignolij perfect! now let's wait for AWS guys 😅

**Comment by normj** [comment]
AWS Guy back from the winter holidays and ready to take a look 😄 

So this is odd that `DefaultRegion` is even showing up. That should be being replaced with either an empty string or whatever you pass in with the `--region` flag from the `dotnet new` command. We need to figure out and fix why `DefaultRegion` is showing up for you because that will be a problem in not just this library but any of our AWS libraries.

My suspicion is the command line templates are being used now from the `dotnet new` command but from Visual Studio. For Visual Studio users we expect users to be creating the Lambda project from the built in project templates from the [AWS Toolkit for Visual Studio](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2022) which has the logic to swap out the `DefaultRegion` to whatever is configured in the AWS Explorer inside VS. Can you confirm where you created the project?

**Comment by brignolij** [comment]
Hi @normj,
I used Visual Studio using the visual interface (check images) to create the serverless application. Not the command line.
Is there another way to create project ?

Regards
screenshot 2023-01-05 à 15 58 45
screenshot 2023-01-05 à 16 00 13

**Comment by normj** [comment]
Sorry about getting delayed responding to this. I reproduced the issue in the toolkit and have submitted a PR toolkit to the IDE team to fix the issue so that `DefaultRegion` won't show up. Given that the problem will be fixed in the toolkit I don't think we need to put a warning in the README file.

Thanks for letting me know about the issue!

**Pull request closed without merging**
