### PR TITLE
Added  `Filters` property to SystemsManagerConfigurationSource 

### PR DESCRIPTION
**Pull request by zahycs**
Added **Filters** to configuration source, this is to be used to add extra filters  when getting parameters by path.

## Description
Adding Filters property (Parameter filter ) gives us the ability to add extra filters  when getting parameters by path, for example a set of parameters labeled with a specific release version, or a certain tag filter and so on.

## Motivation and Context
with the Path, Filters could be used to retrieve a specific filtered parameters set, for example a set of parameters labeled with a specific release version,  

## Testing
- I added unit tests that cover the change 
- Used the the new change in a sample app, deployed it, and I was able to load the parameters that have 
   the provided label correctly.
- tested that the sample app loads the latest version of the parameters (default) if no label is provided. 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

## License
- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-dotnet-extensions-configuration/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by zahycs** [comment]
Related to this issue : https://github.com/aws/aws-dotnet-extensions-configuration/issues/43

**Comment by KenHundley** [comment]
Hey @zahycs,

It would probably be better long term to do this in a more extinstible way. That way future requests for other filter types, multiple label support, etc. can be introduced without breaking changes. 

I would suggest something more similar to this:
```csharp
config.AddSystemsManager(source =>
{
    source.Path = "/myapp";
    source.Filters.Add(new LabelFilter { Values = { "Label1", "Label2" } });
    source.Filters.Add(new TagFilter { Name = "mytag", Values = { "TagValue1", "TagValue2" } });
});
```

It doesn't need to be exactly this, but something that allows for future enhancements.

**Comment by zahycs** [comment]
> Hey @zahycs,
> 
> It would probably be better long term to do this in a more extinstible way. That way future requests for other filter types, multiple label support, etc. can be introduced without breaking changes.
> 
> I would suggest something more similar to this:
> 
> ```cs
> config.AddSystemsManager(source =>
> {
>     source.Path = "/myapp";
>     source.Filters.Add(new LabelFilter { Values = { "Label1", "Label2" } });
>     source.Filters.Add(new TagFilter { Name = "mytag", Values = { "TagValue1", "TagValue2" } });
>     source.Filters.Add(new TypeFilter { Values = { "SecureString" } });
>     source.Filters.Add(new TierFilter { Values = { "Standard" } });
> });
> ```
> 
> It doesn't need to be exactly this, but something that allows for future enhancements.

Hi @KenHundley , 
Thank you for the comment, I do agree, however I suggested the same here #43 , but @klaytaybai thought a `Label` property might be more consistent with `Path` property,  but I really prefer what you suggest!

**Comment by zahycs** [comment]
Hi again @KenHundley, 
I've updated the PR, it's now similar to what you suggested, please let me know what do you think. 
```cs 
config.AddSystemsManager(configurationSource =>
{
    configurationSource.Path =  "/myapp";
    configurationSource.Filters.Add(new ParameterStringFilter
          {
              Key = "Label",
              Option = "Equals",
              Values = { "Value1","Value2" }
           }); 
});
```

**Comment by normj** [comment]
Thanks for the PR. I pushed out version 1.2.0 with this PR.

**Pull request merged**
