### PR TITLE
Only trigger OnReload() when values have changed

### PR DESCRIPTION
**Pull request by KenHundley**
## Description
Addresses an issue brought up in #29.
With this change, the new and old data dictionaries are compared and the OnReload method is only called if the dictionaries differ.

I also removed some unnecessary whitespace in a couple files

## Testing
All unit tests pass, and I did additional verification of the functionality change through manual testing

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-dotnet-extensions-configuration/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by KenHundley** [comment]
Sry @normj for changing things. You got to this faster than I thought :)

**Comment by KenHundley** [comment]
I'm also done now btw, unless you would like any changes

**Comment by normj** [comment]
No worries. Thanks for taking the time to do the PR.

**Comment by sstevenkang** [comment]
@KenHundley  could you rebase this again?  I'll merge both PRs in and do a release.

**Comment by KenHundley** [comment]
Hey Steven, I was actually going to close this PR. The other one also contains this update.

Let me know if you'd rather me update this or close it.

**Comment by KenHundley** [comment]
Actually, I'm going to go ahead and close this. I just double checked that all of this already exists in the other PR.

**Pull request closed without merging**
