### PR TITLE
Add support for an appsettings-like format of the parameter value

### LINKED ISSUE #51: Using SSM parameter as ConfigurationSection
Is it possible to use SSM parameter as ConfigurationSection?

For example parameter with name /example/settings/Logging
with json value

```
{
"Level": "Information",
"SomethingElse": "Test"
}
```
And then use it like this?
```
public class Logging
{
    public string Level { get; set; }
    public string SomethingElse{ get; set; }
}

...

var configurationSection = configuration.GetSection(nameof(Logging));
services.Configure<Logging>(configurationSection);
```

### PR DESCRIPTION
**Pull request by warej**
This code allows to use SSM parameter store as ConfigurationSection, so solves #51 .

## Description

The change lets the library user decide how much parameters are stored as one Parameter Store value.

## Motivation and Context

It fixes #51.
It is also an alternative to #54, with the following pros:
* Less breaking change - people, that already integrated with previous versions should have no problem with porting to the new version. However, their build will still failed if they implemented IParameterProcessor directly, instead of extending the DefaultParameterProcessor
* JsonParameterProcessor included in the project, so that everyone can easily use it

## Testing

Solution covered with unit tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-dotnet-extensions-configuration/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by DanielSlessarevTR** [comment]
Would love to see this change in an upcoming version release

**Comment by aziz-shahed-cko** [comment]
Hi, is there any update on this? Would be a great addition for us to be able to move entire section of app settings to a single parameter than just one at a time.

**Comment by ignas-sakalauskas-cko** [comment]
Hi Team, do you have any update on including this feature..?

**Comment by normj** [comment]
I have created PR [#103 ](https://github.com/aws/aws-dotnet-extensions-configuration/pull/103) that consolidates this open PRs along with this change. Because of the breaking changes across the PRs including this one I am planning on a major version bump to 4.

I'm going to close this PR and track the work in #103. Please feel free to review that PR for the changes I made from this PR.

**Comment by warej** [comment]
Not exactly helping in my case, as we are still stuck with .Net Framework 4.8, but still good to see that it was taken seriously.

**Pull request closed without merging**
